### ISSUE TITLE
Create Time-Picker for non-Chrome/iPhone browsers

### ISSUE THREAD

**Issue by Mayuranatha** [Himalayan-Academy/pk-vehicle-signup#10]
When not using Chrome or iPhone, there is currently no time picker.

**Comment by soapdog** [comment]
Firefox has not yet implemented the native UI for such pickers. I will implement a HTML5 based one and get back here.

**Comment by Mayuranatha** [comment]
Tried out the new time picker. It works.

One thing though, the picker shows 12h time but the field shows 24h time. It's a little strange to see 24h show up when you're picking 12h. Is it possible to make both show up as 12h time?

**Comment by soapdog** [comment]
Actually, the time needs to be 24h, I could show a "fake time in 12h format" and convert it behinds the scene but it will involve changing some stuff. Do you think it is worthy it?

**Comment by Mayuranatha** [comment]
Actually yes,.... Most of us are not used to using 24h time, and I want to make it as easy as possible to use. Unless it involves a serious reworking let's change it to show 12h time.



-Mayuranatha
________________________________

**Comment by Mayuranatha** [comment]
Time picker works great! 12h shows.

**Comment by soapdog** [comment]
Thanks for the feedback! Closing this one!
