### ISSUE TITLE
Changing date on current reservation error

### ISSUE THREAD

**Issue by Mayuranatha** [Himalayan-Academy/pk-vehicle-signup#14]
If you create a reservation, then change the date, it won't move the reservation. It creates another reservation that is blank on the new date, and keeps the old one. This would be needed if you accidentally created a reservation on a wrong day or need to move it because the appointment changed, without needing to rewrite everything all over again.

**Comment by soapdog** [comment]
This is working fine here as can be seen on the following gif:

![change_date](https://user-images.githubusercontent.com/23247/26996284-d2f8bf38-4d47-11e7-8029-e7e52cff98c7.gif)

Are you using the latest version?

**Comment by Mayuranatha** [comment]
You are correct! False alarm. Not sure what happened. I just tried it again and it works fine. We can close this :)
