### ISSUE TITLE
Dates do not sort

### ISSUE THREAD

**Issue by Mayuranatha** [Himalayan-Academy/pk-vehicle-signup#15]
The reservations sort based on the time the reservation was entered not the reservation date itself. So a reservation that starts at 10am can show up first and a reservation that starts at 8am can show up second.

Possible to have the reservations sort by start time?

**Comment by soapdog** [comment]
working on it...

**Comment by soapdog** [comment]
I just double checked and it is sorting, it has explicit code to sort dates as can be seen in ```Home.php```:

```
 public function get_reservations_for_car($car, $day) {
        $this->logger->info("Get Reservations:", $day);

        $reservations = ORM::for_table("reservation")
            ->where("car_id", $car["car_id"])
            ->where_like("start", substr($day["Date_"], 0, 10) . "%")
            ->order_by_asc("start")
            ->find_array();

        $this->logger->info("SQL: " . ORM::get_last_query());


        return $reservations;
    }
```

I just added some entries here and it sorted correctly.

**Comment by Mayuranatha** [comment]
So sorry, not sure what happened again! Just tested it and it works great. We can close this too.
