### ISSUE TITLE
Chrome and iPhone not saving

### ISSUE THREAD

**Issue by Mayuranatha** [Himalayan-Academy/pk-vehicle-signup#8]
Chrome and iPhone not saving reservations.

**Comment by soapdog** [comment]
Already working on Chrome, needs testing on iPhone.

**Comment by soapdog** [comment]
@Mayuranatha can you test the latest commit on iPhone please? I don't have an iPhone handy right now... I tested on Chrome and it works.

**Comment by Mayuranatha** [comment]
@soapdog It Works! Was able to create, edit and delete reservation with the date auto-populating both on the iPhone and on Chrome... Great work!

**Comment by soapdog** [comment]
Perfect! Closing this issue then! 😸
